name: rapids_env

channels:
  - blazingsql
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask-sql
  - cudatoolkit=11.2
  - cudnn=7.6
  - dask=2.14
  - datashader=0.10
  - ipython-sql=0.3
  - jupyterlab=1.2
  - jupyterlab-git=0.9
  - matplotlib=3.2
  - nbdime=1.1
  - nodejs=13
  - numba=0.58
  - pandas=1.4
  - panel=0.6
  - pip=20.0
  - pip:
    - -r file:requirements.txt
  - pyarrow=0.15
  - python=3.9
  - python-flatbuffers=1.11
  - scikit-image=0.19
  - scikit-learn=1.1
  - rapids=22.08
  - xgboost=1.0
