name: rapids_env

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python>=3.8,<3.9.0a0
  - rapids=22.08
  - cudatoolkit=11.2
  - dask-sql=2022.8.0
  - jupyterlab=3.4.5
  - dash=2.6.1
  - graphistry=0.27.1
  - pycaret=2.2.3
  - xarray-spatial=0.3.5
  - jupyterlab-nvdashboard=0.7.0
  - jax=0.3.17
  - jaxlib=0.3.15
  - ray-tune=1.12.0
  - imbalanced-learn=0.9.1
  - jupyterlab-git=0.39.1
  - xeus-python=0.14.3
  - hvplot=0.8.1
  - s3fs=2022.8.2
  - openssl=1.1.1q
  - gcsfs=2022.8.2
  - pip=22.1.2
