name: rapids_env

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask=2022.01.0
  - dask-sql=2022.1.0
  - cudatoolkit=11.5
  - datashader=0.14.1
  - ipython-sql=0.3.9
  - jupyterlab=3.4.5
  - jupyterlab-git=0.39.1
  - matplotlib=3.5.2
  - nbdime>=3.1
  - nodejs=18.8.0
  - numba=0.55.1
  - pandas=1.4.3
  - panel=0.13.1
  - pip=22.1.2
  - pip:
    - -r file:requirements.txt
  - pyarrow=8.0.0
  - python=3.8
  - python-flatbuffers=2.0
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - rapids=22.08
  - xgboost=1.5.0
