name: rapids_env

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - rapids=22.08
  - cudatoolkit=11.5
  - python=3.9
  - pip=22.1.2
  - pip:
    - -r file:requirements.txt

